### ISSUE TITLE
how to auto fit the cells

### ISSUE THREAD

**Issue by 111100001** [BreadPitch/THE-RTSS-Overlay#2]
i loaded the overlay but it looks overlapping with other texts and number and it is hard to read 

![image](https://github.com/user-attachments/assets/2bcf1a52-5b86-4a15-9fa7-a082d60f0126)

is there a way to increase the the horizontal size to make the text fit?

**Comment by BreadPitch** [comment]
Hey, thanks for asking end enjoying the Overlay. The solution is easy, you just need to set the font to Lato / size 7, as described in the readme, then it´s as beautiful as in the screenshots.

**Comment by BreadPitch** [comment]
Please report back if it works, I will then close the issue.

**Comment by 111100001** [comment]
oh thank you its perfect now. i love the overlay.
i over looked that part of the instructions bc i thought it was an alternative way to install lol



![image](https://github.com/user-attachments/assets/42d80bd0-2aaa-4486-9392-be4a96f8c5e1)

**Comment by BreadPitch** [comment]
Greast to hear, thanks! I just see, you should also copy the content of the image folder, so you have the CPU & GPU logos.

So you just loaded the. ovl, you did not copy the entire folder structure to the installation folder?

**Comment by 111100001** [comment]
i put the whole folder in the installation directory. did not do anything
else. that's it. should i but the subfolders where they belong in their
respective RTSS folders?

**Comment by BreadPitch** [comment]
Yes, the content of the subfolders in the respective installation subfolder. Unpack, and copy the entire folder structure in the "first folder" over to the RTSS root folder. That is the way. Then you should see the logos, and also Lato should have worked OOB.

**Comment by 111100001** [comment]
ok i just did that and it is showing logos 
![image](https://github.com/user-attachments/assets/fd66df24-b61e-47cb-bef5-8b0f94ddea44)

i just moved and replaced the folders of Riva Tuner with the folders of this zip but that might be a problem for people who have other overlays. however it is working fine for me, thank you very much!

**Comment by BreadPitch** [comment]
Perfect! This should not be an issue at all, as the folders are not replaced, it just adds new files to the folders (.ovl, .png, ttf), and replaces exisiting config files (.cfg) so it works OOTB. Copying the folder structure does not delete existing files.

**Comment by 111100001** [comment]
oh got it thanks

**Comment by BreadPitch** [comment]
Issue solved - solution is to extract the .zip, go into the first folder, and copy the entire content (files + subfolders) to the RTSS installation directory.

Or do a manual installation following all the steps described in the readme.
